# ******************************************************************* #
# * useful commands:
#   * `pre-commit install`  # install the pre-commit hooks
#   * `pre-commit autoupdate`
#   * `pre-commit run --all-files`
# ******************************************************************* #

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]  # prevent running on Jupyter notebooks
        args: [ --fix ]  # enable lint fixes
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]  # prevent running on Jupyter notebooks
  # too long to run
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       language: system
  #       types: [python]
  # - repo: local
  #   hooks:
  #     - id: interrogate
  #       name: interrogate
  #       entry: interrogate
  #       language: system
  #       pass_filenames: false  # needed if excluding files with pyproject.toml or setup.cfg
  # - repo: local
  #   hooks:
  #     - id: isort
  #       name: isort
  #       entry: isort
  #       language: system
