# ************************************************************************** #
# Deploys Docker image to AWS ECR and then updates AWS Lambda with the image.
#
# Uses whoan/docker-build-with-cache-action to cache the Docker image to
# speed up build times. Does so by creating a second AWS ECR repo with
# [-stage] at the end to pull cached images from.
#
# Must define the env vars at the top of the file with your specific ones.
#
# Must specify the following GitHub secrets:
#   * AWS_ACCESS_KEY_ID
#   * AWS_SECRET_ACCESS_KEY
#   * AWS_ECR_IMAGE_URI
# ************************************************************************** #

name: AWS Lambda Deploy - SNS Email Notification Order Created

on:
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # trigger manually

env:
  ECR_IMAGE_TAG: latest
  # ECR_IMAGE_TAG: ${{ github.sha }}
  AWS_ECR_REPOSITORY_NAME: sandbox/flask-microservices/sns-email-notification-order-sent
  AWS_LAMBDA_FUNC_NAME: sandbox-alex-rest-api-order-created-email-sns-lambda
  AWS_DEFAULT_REGION: us-east-1
  WORKING_DIRECTORY: ./src_api_gateway/lambda_email_notification

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@main

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$AWS_ECR_REPOSITORY_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$AWS_ECR_REPOSITORY_NAME:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$AWS_ECR_REPOSITORY_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
        --function-name ${{ env.AWS_LAMBDA_FUNC_NAME }} \
        --image-uri "${{ secrets.AWS_ECR_IMAGE_URI_LAMBDA_AUTHORIZER }}:${{ env.ECR_IMAGE_TAG }}"
      env:
        AWS_LAMBDA_FUNC_NAME: ${{ env.AWS_LAMBDA_FUNC_NAME }}
