name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # * https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r src_api_gateway/auth_service/requirements.txt
        pip install -r src_api_gateway/dummy_service/requirements.txt
        pip install -r src_api_gateway/order_service/requirements.txt
        pip install -r src_api_gateway/web_service/requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_SSL: ${{ secrets.REDIS_SSL }}
        SESSION_EXPIRE_TIME_SECONDS: ${{ secrets.SESSION_EXPIRE_TIME_SECONDS }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      run: |
        python -m pytest tests/auth_service
        python -m pytest tests/dummy_service
        python -m pytest tests/order_service
        python -m pytest tests/web_service