name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AUTH_SERVICE_URL_REST_API: "https://lk354d3w02.execute-api.us-east-1.amazonaws.com/dev/auth"
  ORDER_SERVICE_URL_REST_API: "https://lk354d3w02.execute-api.us-east-1.amazonaws.com/dev/orders"

jobs:
  test:
    runs-on: ubuntu-latest

    # * https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache dependencies (linux)
      uses: actions/cache@main
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache dependencies (windows)
      uses: actions/cache@main
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv  # faster way to install dependencies
        python -m uv pip install flake8 mypy isort pytest bandit pylint interrogate wheel setuptools --system
        python -m uv pip install pytest pytest-mock requests_mock

        # flake8-pyproject - for loading flake8 with toml config (https://github.com/microsoft/vscode-flake8/issues/135)
        python -m uv pip install flake8-pyproject --system

        python -m uv pip install -r src_api_gateway/auth_service/requirements.txt
        python -m uv pip install -r src_api_gateway/dummy_service/requirements.txt
        python -m uv pip install -r src_api_gateway/order_service/requirements.txt
        python -m uv pip install -r src_api_gateway/web_service/requirements.txt

        if [ -f requirements_stubs.txt ]; then python -m uv pip install -r requirements_stubs.txt --system; fi

    - name: Lint with flake8
      id: flake8
      continue-on-error: true  # will check failure after
      run: |
        if [ -f "pyproject.toml" ]; then flake8 --toml-config=pyproject.toml .; else flake8 .; fi

    - name: Lint with mypy
      id: mypy
      continue-on-error: true  # will check failure after
      run: |
        mypy .

    - name: Lint with pylint  # must have __init__.py in top directory to run recursively
      id: pylint
      continue-on-error: true  # will check failure after
      run: |
        pylint *

    - name: Lint with interrogate (docstring checker)
      id: interrogate
      continue-on-error: true  # will check failure after
      run: |
        interrogate .

    - name: Lint with isort
      run: |
        # --diff: Prints a diff of all the changes isort would make to a file
        isort . --diff;
        echo $"isort_errors";

    - name: check any `flake8`, `mypy`, `pylint`, `interrogate` checks failed
      if: |
        (steps.flake8.outcome != 'success') ||
        (steps.mypy.outcome != 'success') ||
        (steps.pylint.outcome != 'success') ||
        (steps.interrogate.outcome != 'success')
      run: |
        echo "one or all of flake8, mypy, pylint, or interrogate failed"
        exit 1

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_SSL: ${{ secrets.REDIS_SSL }}
        SESSION_EXPIRE_TIME_SECONDS: ${{ secrets.SESSION_EXPIRE_TIME_SECONDS }}
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        python -m pytest tests/web_service

    - name: Run bandit (security checks)
      run: |
        if [ -f "pyproject.toml" ]; then bandit -r . -c "pyproject.toml"; fi
